import { useState, useMemo } from 'react';
import { Link } from 'react-router-dom';
import { useAuth } from '../context/AuthContext';
import { useQuotes } from '../hooks/useQuotes';
import { useClients } from '../hooks/useClients';
import { useUsers } from '../hooks/useUsers';
import { formatMoney } from '../utils/formatters';
import Header from '../components/layout/Header';
import GlassPanel from '../components/ui/GlassPanel';
import StatsGrid from '../components/dashboard/StatsGrid';
import CRMTable from '../components/dashboard/CRMTable';
import AdminStats from '../components/dashboard/AdminStats';
import ClientDetailModal from '../components/dashboard/ClientDetailModal';

export default function DashboardPage() {
  const { user, getRoleName } = useAuth();
  const { quotes, loading: loadingQuotes, updateQuoteStatus } = useQuotes(user?.id, user?.role, user?.storeId);
  const { clients, loading: loadingClients } = useClients();
  const [selectedClient, setSelectedClient] = useState(null);

  // Quotes are already filtered by role in useQuotes hook
  const dashboardQuotes = quotes;

  // Group quotes by client ID to attach them to clients
  const clientQuotesMap = useMemo(() => {
    const map = {};
    quotes.forEach((q) => {
      const cid = q.clientId || (q.client?.email ? `temp-${q.client.email}` : null);
      if (!cid) return;
      if (!map[cid]) map[cid] = [];
      map[cid].push(q);
    });
    return map;
  }, [quotes]);

  // Filter and map clients with their quotes
  const filteredClients = useMemo(() => {
    if (!clients) return [];
    
    // Attach quotes to each client
    const clientsWithQuotes = clients.map(client => {
      const clientQuotes = clientQuotesMap[client.id] || 
        quotes.filter(q => q.client?.name === client.name && q.client?.email === client.email);
        
      return {
        ...client,
        quotes: clientQuotes
      };
    });

    // Sort clients: those with quotes first (by most recent quote date), 
    // then those without quotes by creation date.
    let sorted = [...clientsWithQuotes].sort((a, b) => {
      const aDate = a.quotes?.length > 0 ? new Date(a.quotes[0].date).getTime() : new Date(a.createdAt || 0).getTime();
      const bDate = b.quotes?.length > 0 ? new Date(b.quotes[0].date).getTime() : new Date(b.createdAt || 0).getTime();
      return bDate - aDate;
    });

    if (user?.role === 'admin' || user?.role === 'manager') {
      return sorted;
    }

    // vendor: only clients with quotes generated by this vendor
    return sorted.filter((c) => c.quotes?.some((q) => q.userId === user?.id));
  }, [clients, user]);

  return (
    <div className="min-h-screen flex flex-col">
      {/* Background decorations */}
      <div className="fixed top-[-10%] left-[-10%] w-[40vw] h-[40vw] rounded-full bg-blue-400/5 blur-[120px] z-[-1]"></div>
      <div className="fixed bottom-[-10%] right-[-10%] w-[35vw] h-[35vw] rounded-full bg-cyan-400/5 blur-[100px] z-[-1]"></div>

      <Header />

      <main className="flex-grow max-w-7xl mx-auto px-4 py-8 md:py-10 w-full space-y-8 relative z-10">
        {/* Welcome */}
        <div className="flex flex-col md:flex-row md:items-center md:justify-between gap-4">
          <div>
            <h1 className="text-3xl md:text-4xl font-bold text-brand-dark mb-1">
              ¡Hola, {user?.name}!
            </h1>
            <p className="text-slate-500">
              <span className="px-2 py-0.5 rounded-full text-xs font-bold bg-brand-light text-brand-blue">
                {getRoleName(user?.role)}
              </span>
              <span className="ml-3 text-sm">
                {new Date().toLocaleDateString('es-MX', { weekday: 'long', day: 'numeric', month: 'long' })}
              </span>
            </p>
          </div>
          <Link
            to="/quoter"
            className="bg-brand-blue text-white font-bold py-3 px-6 rounded-2xl hover:bg-blue-600 transition-all shadow-lg hover:shadow-xl flex items-center gap-2 w-fit"
          >
            <i className="fas fa-plus"></i> Nueva Cotización
          </Link>
        </div>

        {/* Stats */}
        {user?.role === 'admin' ? (
          <div className="mb-8">
            <h2 className="text-xl font-bold text-brand-dark mb-4">Panel Global (Admin)</h2>
            <AdminStats />
          </div>
        ) : (
          <StatsGrid quotes={dashboardQuotes} />
        )}

        {/* CRM Table */}
        <GlassPanel>
          <div className="flex items-center justify-between mb-6">
            <h2 className="text-lg font-bold text-brand-dark">
              <i className="fas fa-users mr-2 text-brand-blue"></i>
              Últimos Clientes
            </h2>
            <Link to="/crm" className="text-sm font-bold text-brand-blue hover:text-brand-dark transition-colors">
              Ver todos <i className="fas fa-arrow-right ml-1"></i>
            </Link>
          </div>
          <CRMTable
            clients={filteredClients.slice(0, 5)}
            loading={loadingQuotes || loadingClients}
            onClientClick={(client) => setSelectedClient(client)}
            showVendor={user?.role === 'manager' || user?.role === 'admin'}
            isAdmin={user?.role === 'admin'}
            onUpdateQuoteStatus={updateQuoteStatus}
          />
        </GlassPanel>
      </main>

      {/* Client Detail Modal */}
      <ClientDetailModal
        client={selectedClient}
        quotes={selectedClient?.quotes || []}
        isOpen={!!selectedClient}
        onClose={() => setSelectedClient(null)}
        isAdmin={user?.role === 'admin'}
        onUpdateQuoteStatus={updateQuoteStatus}
      />
    </div>
  );
}
